### ISSUE TITLE
train_batch_correction AttributeError: 'DataFrame' object has no attribute 'as_matrix'

### ISSUE THREAD

**Issue by ashipde** [KrishnaswamyLab/SAUCIE#21]
I am attempting to use SAUCIE in Python 3.7.4 with tensorflow 1.4.0. My goal is to batch-correct and cluster CyTOF data. FCS files are the input data and are in folder _fcs_.

`SAUCIE.py --format fcs --input_dir fcs --output_dir out --batch_correct --cluster`

Can you tell me why I might be getting this error (which also occurs if I use CSV instead of FCS files)? Below is the terminal output. 

Thanks.

ps. SAUCIE appears to be a great software. I really hope it gets some good documentation. 

```
Training batch correction models.
Starting to train 1 batch correction models...
Training model 0
Traceback (most recent call last):
  File "/software/SAUCIE/SAUCIE.py", line 338, in <module>
    train_batch_correction(rawfiles)
  File "/software/SAUCIE/SAUCIE.py", line 128, in train_batch_correction
    raise(ex)
  File "/software/SAUCIE/SAUCIE.py", line 111, in train_batch_correction
    alldata = np.concatenate([refx.as_matrix(), nonrefx.as_matrix()], axis=0)
  File "/lib/python3.7/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'as_matrix'
```

**Comment by ashipde** [comment]
I am able to fix this issue by changing the four instances of _to_matrix()_ in SAUCIE.py to _to_numpy()_.
